# ===================================================================
# CONFIG VERSION: v2.8.0-Stable
# ===================================================================
SYSTEM_LANGUAGE="ru"
EXIT_NODE_VPN_NAME="WG-Zhmyak2"
EXIT_NODE_INTERNAL_IP="10.151.0.3"
CHECK_HOSTS="1.1.1.1 9.9.9.9 8.8.8.8"

INTERNET_FORWARD_NETS="
192.168.6.0/24
192.168.5.0/24
10.11.12.0/24
192.168.10.0/24
192.168.3.0/24
"

# --- НАСТРОЙКИ МОДУЛЯ ИСКЛЮЧЕНИЙ (BYPASS) ---
ENABLE_BYPASS_MODULE="true"

# --- НАСТРОЙКИ МОДУЛЯ ДАТА-ЦЕНТРА (IPSec) ---
ENABLE_DATACENTER_ROUTING="true"
DC_IPSEC_TUNNEL_NAME="CP-DC.IPSEC"
DATACENTER_ALLOWED_NETS="
192.168.6.0/24
192.168.5.0/24
192.168.10.0/24
"

# --- НАСТРОЙКИ МОДУЛЯ УВЕДОМЛЕНИЙ ---
ENABLE_TELEGRAM="false"
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""

# --- НАСТРОЙКИ МОДУЛЯ КОНТРОЛЯ СВЯЗИ (Watchdog) ---
ENABLE_WATCHDOG="true"
WATCHDOG_INTERVAL_MINUTES="15"
